### ISSUE TITLE
investigate using Treiber Stack

### ISSUE THREAD

**Issue by yoshuawuyts** [rylev/remem#3]
I think this would be almost a perfect replacement for the mutex of vec T, as it's generic over T and can be put in an Arc without any issues!

Unfortunately it's not a standalone module, but we could easily copy it over into our source.

https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-epoch/examples/treiber_stack.rs

**Comment by rylev** [comment]
This is fixed with #5
